micronaut:
  application:
    name: frankenaut
datasources:
  default:
    url: jdbc:h2:mem:frankendb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: frankenuser
    password: frankenpass
    schema-generate: CREATE_DROP
    dialect: H2
jpa.default.properties.hibernate.hbm2ddl.auto: update
